### ISSUE TITLE
Why you use `.` for padding?

### ISSUE THREAD

**Issue by SeanSilke** [commenthol/url-safe-base64#4]
Why do you use `.` for padding when according to RFC https://www.rfc-editor.org/rfc/rfc4648 in "URL and Filename safe" Base 64 alphabet padding character is `=`?

**Comment by commenthol** [comment]
Good point. Honestly speaking, no idea. 
Thanks for sharing the spec. Will update the package. Standards first...

**Comment by commenthol** [comment]
Hi @SeanSilke, Can you please review the changes made in #5?

**Comment by SeanSilke** [comment]
Hello @commenthol! Thank you for for such a quick response.  The code in https://github.com/commenthol/url-safe-base64/pull/5 Is looking fine for me.

**Comment by commenthol** [comment]
👍
